export const dynamic = "force-static";

// Stylesheet that renders sitemap XML as a styled table in the browser
// (Google still reads the raw XML). Handles both <sitemapindex> and <urlset>.
const XSL = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
  <xsl:output method="html" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>XML Sitemap &#8212; telugulo.in</title>
        <style>
          :root{--blue:#4c6ef5;--ink:#1d1d1d;--line:#e7e9f0;--mute:#6b7280}
          *{box-sizing:border-box}
          body{margin:0;font-family:-apple-system,system-ui,'Segoe UI',Roboto,sans-serif;color:var(--ink);background:#fff}
          .hero{background:var(--blue);color:#fff;padding:34px 24px}
          .hero h1{margin:0 0 8px;font-size:30px}
          .hero p{margin:0;max-width:940px;line-height:1.6;opacity:.96}
          .wrap{max-width:1100px;margin:26px auto;padding:0 20px}
          .count{color:var(--mute);font-size:14px;margin:0 0 14px}
          table{width:100%;border-collapse:collapse;font-size:14px;border:1px solid var(--line);border-radius:8px;overflow:hidden}
          thead th{background:var(--blue);color:#fff;text-align:left;padding:12px 16px;font-weight:700}
          tbody td{padding:11px 16px;border-bottom:1px solid var(--line)}
          tbody tr:nth-child(even){background:#f7f8fa}
          tbody tr:last-child td{border-bottom:0}
          a{color:#2660d4;text-decoration:none}
          a:hover{text-decoration:underline}
          .lm{white-space:nowrap;color:#374151}
          .foot{color:var(--mute);font-size:12px;margin:18px 0 40px}
        </style>
      </head>
      <body>
        <div class="hero">
          <h1>XML Sitemap</h1>
          <p>This XML Sitemap is generated by <strong>telugulo.in</strong>. It is what search engines like Google use to crawl and re-crawl posts, pages and categories on the site.</p>
        </div>
        <div class="wrap">
          <xsl:if test="s:sitemapindex">
            <p class="count">This sitemap index contains <xsl:value-of select="count(s:sitemapindex/s:sitemap)"/> sitemaps.</p>
            <table>
              <thead><tr><th>Sitemap</th><th>Last Modified</th></tr></thead>
              <tbody>
                <xsl:for-each select="s:sitemapindex/s:sitemap">
                  <tr>
                    <td><a href="{s:loc}"><xsl:value-of select="s:loc"/></a></td>
                    <td class="lm"><xsl:call-template name="fmt"><xsl:with-param name="d" select="s:lastmod"/></xsl:call-template></td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>
          <xsl:if test="s:urlset">
            <p class="count">This sitemap contains <xsl:value-of select="count(s:urlset/s:url)"/> URLs.</p>
            <table>
              <thead><tr><th>URL</th><th>Images</th><th>Last Modified</th></tr></thead>
              <tbody>
                <xsl:for-each select="s:urlset/s:url">
                  <tr>
                    <td><a href="{s:loc}"><xsl:value-of select="s:loc"/></a></td>
                    <td><xsl:value-of select="count(image:image)"/></td>
                    <td class="lm"><xsl:call-template name="fmt"><xsl:with-param name="d" select="s:lastmod"/></xsl:call-template></td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>
          <p class="foot">telugulo.in &#183; Telugu Tech &amp; AI News</p>
        </div>
      </body>
    </html>
  </xsl:template>

  <xsl:template name="fmt">
    <xsl:param name="d"/>
    <xsl:choose>
      <xsl:when test="contains($d,'T')">
        <xsl:value-of select="substring-before($d,'T')"/>
        <xsl:text> </xsl:text>
        <xsl:value-of select="substring(substring-after($d,'T'),1,5)"/>
        <xsl:text> +00:00</xsl:text>
      </xsl:when>
      <xsl:otherwise><xsl:value-of select="$d"/></xsl:otherwise>
    </xsl:choose>
  </xsl:template>
</xsl:stylesheet>`;

export async function GET() {
  return new Response(XSL, {
    headers: { "content-type": "text/xsl; charset=utf-8" },
  });
}
